# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        # Don't fail CI for small coverage drops
        threshold: 5%
        # Only check against main branch
        target: auto
    patch:
      default:
        # Don't require coverage on new code (relaxed for CLI tool)
        enabled: false

  # Ignore CLI entry point and config loading (hard to unit test)
  ignore:
    - "cmd/**/*"
    - "internal/config/**/*"

comment:
  # Keep PR comments concise
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: true  # Only comment if coverage changed

# Disable PR annotations (reduces noise)
github_checks:
  annotations: false
